<?php
if(!defined('ABSPATH')){ exit; }

//about page settings
acf_add_local_field_group(array(
	'key' => 'group_5c489b8c25cbe',
	'title' => esc_html__('About Page Settings', 'fedcon'),
	'fields' => array(
		array(
			'key' => 'field_5c489b9339058',
			'label' => esc_html__('Intro Section Content', 'fedcon'),
			'name' => 'intro_section_content',
			'type' => 'clone',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'clone' => array(
				0 => 'group_5c45f9c30b235',
			),
			'display' => 'group',
			'layout' => 'block',
			'prefix_label' => 0,
			'prefix_name' => 1,
		),
		array(
			'key' => 'field_5c489bc439059',
			'label' => esc_html__('History Section Content', 'fedcon'),
			'name' => 'history_section_content',
			'type' => 'clone',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'clone' => array(
				0 => 'group_5c45f9c30b235',
			),
			'display' => 'group',
			'layout' => 'block',
			'prefix_label' => 0,
			'prefix_name' => 1,
		),
		array(
			'key' => 'field_5c489bf7a82f9',
			'label' => esc_html__('Government Section Background Image', 'fedcon'),
			'name' => 'government_section_background_image',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'full',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_5c489c06a82fa',
			'label' => esc_html__('Government Section Background Image CSS', 'fedcon'),
			'name' => 'government_section_background_image_css',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c489c16a82fb',
			'label' => esc_html__('Government Section Title', 'fedcon'),
			'name' => 'government_section_title',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c489c21a82fc',
			'label' => esc_html__('Government Section Content', 'fedcon'),
			'name' => 'government_section_content',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'delay' => 0,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page',
				'operator' => '==',
				'value' => '111',
			),
		),
	),
	'menu_order' => 1,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

// team settings
acf_add_local_field_group(array(
	'key' => 'group_5c49dd10e4c8d',
	'title' => esc_html__('Team Settings', 'fedcon'),
	'fields' => array(
		array(
			'key' => 'field_5c49dd1cf154c',
			'label' => esc_html__('Team Section', 'fedcon'),
			'name' => 'team_section',
			'type' => 'clone',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'clone' => array(
				0 => 'field_5c45f9c979584',
				1 => 'field_5c45fe3cc7f88',
				2 => 'field_5c45f9db79585',
				3 => 'field_5c45feedc7f89',
				4 => 'field_5c46023ae4443',
				5 => 'field_5c45f9f079586',
			),
			'display' => 'group',
			'layout' => 'block',
			'prefix_label' => 1,
			'prefix_name' => 1,
		),
		array(
			'key' => 'field_5c49dd5cf154d',
			'label' => esc_html__('Team Members', 'fedcon'),
			'name' => 'team_members',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => 'field_5c49dd68f154e',
			'min' => 0,
			'max' => 0,
			'layout' => 'row',
			'button_label' => esc_html__('Add Team Member', 'fedcon'),
			'sub_fields' => array(
				array(
					'key' => 'field_5c49dd68f154e',
					'label' => esc_html__('Member Name', 'fedcon'),
					'name' => 'member_name',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5c49dd73f154f',
					'label' => esc_html__('Member Position', 'fedcon'),
					'name' => 'member_position',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5c49dd82f1550',
					'label' => esc_html__('Member Image', 'fedcon'),
					'name' => 'member_image',
					'type' => 'image',
					'instructions' => esc_html__('235px x 310px', 'fedcon'),
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'full',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array(
					'key' => 'field_5c49dda3f1551',
					'label' => esc_html__('Member Bio', 'fedcon'),
					'name' => 'member_bio',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 1,
					'delay' => 0,
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page',
				'operator' => '==',
				'value' => '111',
			),
		),
	),
	'menu_order' => 5,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));